namespace superpower_char1Sprites {
    //% fixedInstance jres blockIdentity=images._image
    export const ss111 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss112 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss113 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss114 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss115 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss116 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss117 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss121 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss122 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss123 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss124 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss125 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss126 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss127 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss131 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss132 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss133 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss134 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss135 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss136 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss137 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss141 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss142 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss143 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss144 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss145 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss146 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss147 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss211 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss212 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss213 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss214 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss215 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss216 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss217 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss221 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss222 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss223 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss224 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss225 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss226 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss227 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss231 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss232 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss233 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss234 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss235 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss236 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss237 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss241 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss242 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss243 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss244 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss245 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss246 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss247 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss311 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss312 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss313 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss314 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss315 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss316 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss317 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss321 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss322 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss323 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss324 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss325 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss326 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss327 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss331 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss332 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss333 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss334 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss335 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss336 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss337 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss341 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss342 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss343 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss344 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss345 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss346 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss347 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss511 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss512 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss513 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss514 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss515 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss516 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss517 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss521 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss522 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss523 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss524 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss525 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss526 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss527 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss531 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss532 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss533 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss534 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss535 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss536 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss537 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss541 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss542 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss543 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss544 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss545 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss546 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss547 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss611 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss612 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss613 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss614 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss615 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss616 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss617 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss621 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss622 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss623 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss624 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss625 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss626 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss627 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss631 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss632 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss633 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss634 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss635 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss636 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss637 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss641 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss642 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss643 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss644 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss645 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss646 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss647 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss411 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss412 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss421 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss422 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss431 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss432 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss441 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const ss442 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sst1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sst2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sst3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sst4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sst5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sst6 = image.ofBuffer(hex``);

}
